name: Continous Integration Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: End to End Testing
        uses: cypress-io/github-action@v5
        run: touch env.local
          echo NEXTAUTH_SECRET=${{secrets.NEXTAUTH_SECRET}} >> .env.local
        with:
          build: npm run build
          start: npm run start
