name: Continous Integration Test
on: [ push ]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: End to End Testing
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          JWT_EXPIRY: ${{ secrets.JWT_EXPIRY }}
          CLOUDINARY_URL: ${{ secrets.CLOUDINARY_URL }}
          SECRET: ${{ secrets.SECRET }}

        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run start
          wait-on: "https://www.innovationsgp.com"
