name: Continous Integration Test
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: End to End Testing
        uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000"
        env:
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
          MONGO_URI: ${{secrets.MONGO_URI}}
